# Generated by Django 5.1.7 on 2025-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataloge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='', upload_to='books/'),
            preserve_default=False,
        ),
    ]
